---

- name: amend_hosts_file
  template:
    src:    hosts.j2
    dest:   /etc/hosts
    owner:  root
    group:  root
    mode:   "u=rw,g=r,o=r"

- name: amend_hostname_file
  template:
    src:    hostname.j2
    dest:   /etc/hostname
    owner:  root
    group:  root
    mode:   "u=rw,g=r,o=r"

- name: amend_runtime_hostname
  hostname:
    name: "{{ short_hostname }}"

- name: upgrade_system
  apt:
    update_cache: yes
    upgrade: dist

- name: remove_motd
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/update-motd.d/00-header"
    - "/etc/update-motd.d/10-help-text"
    - "/etc/update-motd.d/50-landscape-sysinfo"

- name: amend_motd
  template:
    src:    00-monokal-header.j2
    dest:   /etc/update-motd.d/00-monokal-header
    owner:  root
    group:  root
    mode:   "u=rwx,g=rx,o=rx"
