---

# Hostname

- name:   amend_hosts_file
  become: true
  template:
    src:   hosts.j2
    dest:  /etc/hosts
    owner: root
    group: root
    mode:  "u=rw,g=r,o=r"

- name: amend_hostname_file
  copy:
    content: "{{ short_hostname }}"
    dest:    /etc/hostname
    owner:   root
    group:   root
    mode:    "u=rw,g=r,o=r"

- name: amend_runtime_hostname
  hostname:
    name: "{{ short_hostname }}"

# MOTD

- name: remove_motd
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/update-motd.d/00-header"
    - "/etc/update-motd.d/10-help-text"
    - "/etc/update-motd.d/50-landscape-sysinfo"

- name: amend_motd
  template:
    src:   "../../../templates/00-monokal-header.j2"
    dest:  "/etc/update-motd.d/00-monokal-header"
    owner: root
    group: root
    mode:  "u=rwx,g=rx,o=rx"

# Packages

- name: install_packages
  apt:
    name:         "{{ item }}"
    update_cache: yes
  with_items:
    - "ntp"
    - "htop"
    - "wget"
    - "curl"
    - "git"
    - "zsh"
  register: install_packages

# Configure NTP

- name: ntp_set_timezone
  when: install_packages|success
  copy:
    content: "Europe/London\n"
    dest:    "/etc/timezone"
    owner:   root
    group:   root
    mode:    "u=rw,g=r,o=r"
  notify:
    - ntp_reconfigure_timezone

# Install Oh-My-Zsh

- name: install_oh_my_zsh
  when: install_packages|success
  shell: "wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh"
  args:
    creates: "~/.ansible_install_oh_my_zsh_lock"
  register: install_oh_my_zsh
  notify:
    - chsh_oh_my_zsh

- name: install_oh_my_zsh_lock
  when: install_oh_my_zsh|success
  copy:
    content: ""
    dest:    "~/.ansible_install_oh_my_zsh_lock"

# Configure Vim

- name: create_vim_dirs
  file:
    path:  "{{ item }}"
    state: directory
  with_items:
    - "~/.vim"
    - "~/.vim/colors"
    - "~/.vim/bundle"
  register: create_vim_dirs

- name: configure_vim_theme
  when: install_packages|success and create_vim_dirs|success
  copy:
    src:   molokai.vim
    dest:  "~/.vim/colors/molokai.vim"

- name: configure_vimrc
  when: install_packages|success and create_vim_dirs|success
  copy:
    src:   vimrc
    dest:  "~/.vimrc"
  register: configure_vimrc

- name: clone_vundle 
  when: install_packages|success and create_vim_dirs|success
  git:
    repo: "https://github.com/gmarik/Vundle.vim.git"
    dest: "~/.vim/bundle/Vundle.vim"
  register: clone_vundle

- name: install_vundle
  when: configure_vimrc|success and clone_vundle|success
  command: "vim +PluginInstall +qall"
  args:
    creates: "~/.ansible_install_vundle_lock"
  register: install_vundle

- name: install_vundle_lock
  when: install_vundle|success
  copy:
    content: ""
    dest:    "~/.ansible_install_vundle_lock"
